// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebKaraoke.Data;

#nullable disable

namespace WebKaraoke.Data.Migrations
{
    [DbContext(typeof(WebKaraokeDbContext))]
    [Migration("20251028090621_AddHinhAnhToMonAn")]
    partial class AddHinhAnhToMonAn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebKaraoke.Data.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<int>("CTHD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CTHD_ID"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<int>("MonID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("CTHD_ID");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("MonID");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.DatPhong", b =>
                {
                    b.Property<int>("DatPhongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatPhongID"));

                    b.Property<DateTime>("GioBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GioKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<int>("PhongID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNguoi")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DatPhongID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("PhongID");

                    b.ToTable("DatPhong");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.DiemThanhVien", b =>
                {
                    b.Property<int>("DiemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiemID"));

                    b.Property<int>("DiemDaSuDung")
                        .HasColumnType("int");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("TongDiem")
                        .HasColumnType("int");

                    b.HasKey("DiemID");

                    b.HasIndex("KhachHangID")
                        .IsUnique();

                    b.ToTable("DiemThanhViens");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.HoaDon", b =>
                {
                    b.Property<int>("HoaDonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonID"));

                    b.Property<int>("DatPhongID")
                        .HasColumnType("int");

                    b.Property<int?>("KM_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("HoaDonID");

                    b.HasIndex("DatPhongID");

                    b.HasIndex("KM_ID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.KhachHang", b =>
                {
                    b.Property<int>("KhachHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhachHangID"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KhachHangID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("SoDienThoai")
                        .IsUnique()
                        .HasFilter("[SoDienThoai] IS NOT NULL");

                    b.ToTable("KhachHang");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.KhuyenMai", b =>
                {
                    b.Property<int>("KM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KM_ID"));

                    b.Property<string>("MaKM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TyLeGiam")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("KM_ID");

                    b.HasIndex("MaKM")
                        .IsUnique();

                    b.ToTable("KhuyenMai");

                    b.HasData(
                        new
                        {
                            KM_ID = 1,
                            MaKM = "KHAI_TRUONG",
                            MoTa = "Khuyến mãi khai trương",
                            NgayBatDau = new DateTime(2025, 10, 18, 16, 6, 20, 391, DateTimeKind.Local).AddTicks(810),
                            NgayKetThuc = new DateTime(2025, 11, 17, 16, 6, 20, 391, DateTimeKind.Local).AddTicks(822),
                            TyLeGiam = 20.00m
                        },
                        new
                        {
                            KM_ID = 2,
                            MaKM = "CUOI_TUAN",
                            MoTa = "Khuyến mãi cuối tuần",
                            NgayBatDau = new DateTime(2025, 10, 23, 16, 6, 20, 391, DateTimeKind.Local).AddTicks(825),
                            NgayKetThuc = new DateTime(2025, 11, 27, 16, 6, 20, 391, DateTimeKind.Local).AddTicks(826),
                            TyLeGiam = 10.00m
                        });
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.LichSuDiem", b =>
                {
                    b.Property<int>("LichSuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichSuID"));

                    b.Property<int>("DiemID")
                        .HasColumnType("int");

                    b.Property<string>("LoaiGiaoDich")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("SoDiemThayDoi")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("LichSuID");

                    b.HasIndex("DiemID");

                    b.ToTable("LichSuDiem");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.MonAnNuocUong", b =>
                {
                    b.Property<int>("MonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonID"));

                    b.Property<bool>("DangKinhDoanh")
                        .HasColumnType("bit");

                    b.Property<string>("DanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HinhAnhUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MonID");

                    b.ToTable("MonAnNuocUong");

                    b.HasData(
                        new
                        {
                            MonID = 1,
                            DangKinhDoanh = true,
                            DanhMuc = "Đồ ăn",
                            DonGia = 50000m,
                            TenMon = "Bò khô"
                        },
                        new
                        {
                            MonID = 2,
                            DangKinhDoanh = true,
                            DanhMuc = "Đồ ăn",
                            DonGia = 40000m,
                            TenMon = "Hạt điều"
                        },
                        new
                        {
                            MonID = 3,
                            DangKinhDoanh = true,
                            DanhMuc = "Đồ ăn",
                            DonGia = 35000m,
                            TenMon = "Khoai tây chiên"
                        },
                        new
                        {
                            MonID = 4,
                            DangKinhDoanh = true,
                            DanhMuc = "Nước uống",
                            DonGia = 25000m,
                            TenMon = "Coca Cola"
                        },
                        new
                        {
                            MonID = 5,
                            DangKinhDoanh = true,
                            DanhMuc = "Nước uống",
                            DonGia = 25000m,
                            TenMon = "Pepsi"
                        },
                        new
                        {
                            MonID = 6,
                            DangKinhDoanh = true,
                            DanhMuc = "Nước uống",
                            DonGia = 15000m,
                            TenMon = "Nước suối"
                        },
                        new
                        {
                            MonID = 7,
                            DangKinhDoanh = true,
                            DanhMuc = "Nước uống",
                            DonGia = 35000m,
                            TenMon = "Trà đào"
                        },
                        new
                        {
                            MonID = 8,
                            DangKinhDoanh = true,
                            DanhMuc = "Nước uống",
                            DonGia = 30000m,
                            TenMon = "Cà phê"
                        });
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.NhanVien", b =>
                {
                    b.Property<int>("NhanVienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienID"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NhanVienID");

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            NhanVienID = 1,
                            ChucVu = "Quản lý",
                            HoTen = "Nguyễn Văn A",
                            SoDienThoai = "0901234567"
                        },
                        new
                        {
                            NhanVienID = 2,
                            ChucVu = "Nhân viên",
                            HoTen = "Trần Thị B",
                            SoDienThoai = "0901234568"
                        });
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.Phong", b =>
                {
                    b.Property<int>("PhongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhongID"));

                    b.Property<decimal>("GiaGio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PhongID");

                    b.HasIndex("TenPhong")
                        .IsUnique();

                    b.ToTable("Phong");

                    b.HasData(
                        new
                        {
                            PhongID = 1,
                            GiaGio = 150000m,
                            LoaiPhong = "VIP",
                            TenPhong = "P001",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            PhongID = 2,
                            GiaGio = 150000m,
                            LoaiPhong = "VIP",
                            TenPhong = "P002",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            PhongID = 3,
                            GiaGio = 100000m,
                            LoaiPhong = "Thuong",
                            TenPhong = "P003",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            PhongID = 4,
                            GiaGio = 100000m,
                            LoaiPhong = "Thuong",
                            TenPhong = "P004",
                            TrangThai = "Trong"
                        });
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanID"));

                    b.Property<int?>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TaiKhoanID");

                    b.HasIndex("KhachHangID")
                        .IsUnique()
                        .HasFilter("[KhachHangID] IS NOT NULL");

                    b.HasIndex("NhanVienID")
                        .IsUnique()
                        .HasFilter("[NhanVienID] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            TaiKhoanID = 1,
                            MatKhauHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("WebKaraoke.Data.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebKaraoke.Data.Entities.MonAnNuocUong", "MonAnNuocUong")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("MonAnNuocUong");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.DatPhong", b =>
                {
                    b.HasOne("WebKaraoke.Data.Entities.KhachHang", "KhachHang")
                        .WithMany("DatPhongs")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebKaraoke.Data.Entities.Phong", "Phong")
                        .WithMany("DatPhongs")
                        .HasForeignKey("PhongID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.DiemThanhVien", b =>
                {
                    b.HasOne("WebKaraoke.Data.Entities.KhachHang", "KhachHang")
                        .WithOne("DiemThanhVien")
                        .HasForeignKey("WebKaraoke.Data.Entities.DiemThanhVien", "KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.HoaDon", b =>
                {
                    b.HasOne("WebKaraoke.Data.Entities.DatPhong", "DatPhong")
                        .WithMany("HoaDons")
                        .HasForeignKey("DatPhongID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebKaraoke.Data.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDons")
                        .HasForeignKey("KM_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebKaraoke.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatPhong");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.LichSuDiem", b =>
                {
                    b.HasOne("WebKaraoke.Data.Entities.DiemThanhVien", "DiemThanhVien")
                        .WithMany("LichSuDiems")
                        .HasForeignKey("DiemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiemThanhVien");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.TaiKhoan", b =>
                {
                    b.HasOne("WebKaraoke.Data.Entities.KhachHang", "KhachHang")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("WebKaraoke.Data.Entities.TaiKhoan", "KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebKaraoke.Data.Entities.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("WebKaraoke.Data.Entities.TaiKhoan", "NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.DatPhong", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.DiemThanhVien", b =>
                {
                    b.Navigation("LichSuDiems");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.KhachHang", b =>
                {
                    b.Navigation("DatPhongs");

                    b.Navigation("DiemThanhVien");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.KhuyenMai", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.MonAnNuocUong", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebKaraoke.Data.Entities.Phong", b =>
                {
                    b.Navigation("DatPhongs");
                });
#pragma warning restore 612, 618
        }
    }
}
